version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:9090
    volumes:
      - .:/app
    ports:
      - "9090:9090"
    environment:
      - DEBUG=True  # Optional, useful for development

volumes:
  - ./db.sqlite3:/app/db.sqlite3
